#!/bin/sh
echo "postinstall: inside `pwd`"
chmod +x dc_crontab fetcher.py
echo "postinstall: chmodded"
crontab dc_crontab
echo "postinstall: crontabbed"
~/current/fetcher.py ~/current/news.shelf
echo "postinstall: DONE"
